name: 'YuChat Send Message'
description: 'Send message to your YuChat instance'
author: YuChat
branding:
  icon: 'send'
  color: 'purple'

# Define your inputs here.
inputs:
  YUCHAT_URL:
    description: 'YuChat API URL'
    required: true
  YUCHAT_TOKEN:
    description: 'YuChat Authentication Token'
    required: true
  YUCHAT_CHANNEL:
    description: 'Base62 YuChat channel id'
    required: true
  YUCHAT_WORKSPACE:
    description: 'Base62 YuChat workspace id'
    required: true
  MARKDOWN:
    description: 'Markdown text for message'
    required: true
  
runs:
  using: node20
  main: dist/index.js
